<section id="blocs" class="blocs-main-container">
    @include('partials.components.blocs-dynamic.bloc_6')
    @include('partials.components.blocs-dynamic.bloc_7')
    @include('partials.components.blocs-dynamic.bloc_8')
    @include('partials.components.blocs-dynamic.bloc_9')
    @include('partials.components.blocs-dynamic.bloc_10')
    @include('partials.components.blocs-dynamic.bloc_11')
    @include('partials.components.blocs-dynamic.bloc_12')
    @include('partials.components.blocs-dynamic.bloc_13')
    @include('partials.components.blocs-dynamic.bloc_14')
    @include('partials.components.blocs-dynamic.bloc_15')
    @include('partials.components.blocs-dynamic.bloc_16')
    @include('partials.components.blocs-dynamic.bloc_17')
    @include('partials.components.blocs-dynamic.bloc_18')
</section>